language: node_js
dist: jammy  # Targets Ubuntu 22.04
node_js:
  # - "14"
  # - "16"
  # - "18"
  # - "20"
  # - "21"
  # - "22"
  # - "23"
  - "24"



before_install:
  - sudo apt-get update
  - sudo apt-get install -y libc6


install: "npm install"
script:
- npm start